### PR TITLE
Docker, Django, MySQL all functioning

### LINKED ISSUE #27: add wildfire data model to django project
depends on #28 
Django uses this common idea of models https://docs.djangoproject.com/en/4.1/topics/db/models/
we would like to generate a model based on the final data schema provided by the sponsor.
As per https://docs.djangoproject.com/en/4.1/howto/legacy-databases/
you should be able to generate models from an existing database

- [x] Connect Docker to Django with working mysql
- [x] Remove sample project models
- [x] Generate a model for final sample schema from sponsors (2019) 
- [x] add this model to the django project and ensure no errors
  - this means ensuring you are able to get records from the database, creating a basic page that lists records may suffice
- [ ] Add 2018 data model
- [ ] Update gitignore for pyc files and migrate name change

### PR DESCRIPTION
**Pull request by jeremystocking**
Closes #27 
Use docker-compose up in f22-fires-wild
Go to http://localhost:8000/data2019/results/

### CODE REVIEW

**Review by collins-benjaminw — CHANGES_REQUESTED** [review]
- we need to gitignore all .pyc files
- please generate a django model for the 2018 data (create table is in main under sql/create_table.sql), name the model "fpa-fod" (possible this will happen another time and we may have a model in the future for "fpa-fod-final")
- what is the "rename_fop_id_data_fod_id" migration meant to do?

**Comment by jeremystocking** [comment]
> * we need to gitignore all .pyc files
> * please generate a django model for the 2018 data (create table is in main under sql/create_table.sql), name the model "fpa-
Will handle this Saturday
> * what is the "rename_fop_id_data_fod_id" migration meant to do?
Just an error on my side... will handle saturday

**Comment by jeremystocking** [comment]
@collins-benjaminw And correct me if I'm wrong but I believe 2018 and 2019 should be separate tables

**Comment by collins-benjaminw** [comment]
> @collins-benjaminw And correct me if I'm wrong but I believe 2018 and 2019 should be separate tables

so, in the end, one table will be all years of fpa-fod-plus. the 2019 data we have was for initial exploration and testing. We can leave it for now, but in the future we won't need separate tables for years

**Pull request merged**
